-- ================================================
-- UNIFICARD - MIGRATION 078
-- UnifyBank Test Currency (TEST) - Moeda fictícia para testes
-- ================================================
--
-- OBJETIVO:
-- Criar suporte para moeda fictícia de teste (TEST) que permite
-- testar fluxos econômicos completos sem usar moedas reais.
--
-- IMPORTANTE:
-- - Esta moeda é EXCLUSIVAMENTE para ambiente de teste/desenvolvimento
-- - NÃO deve ser usada em produção
-- - Todas as transações em TEST devem passar pelo SplitEngine
-- - Ledger registra todas as movimentações normalmente
--
-- ===========================
-- DOCUMENTAÇÃO DA MOEDA TEST
-- ===========================
-- A moeda 'TEST' é uma moeda fictícia de 3 caracteres que:
-- 1. Permite emissão de saldo por administradores
-- 2. Funciona normalmente com todas as transações
-- 3. Passa pelo SplitEngine como qualquer outra moeda
-- 4. É registrada no ledger normalmente
--
-- ESTRUTURA:
-- - accounts.currency pode ser 'TEST' (VARCHAR(3) já suporta)
-- - transactions.currency pode ser 'TEST' (VARCHAR(3) já suporta)
-- - Não há constraint CHECK que impeça 'TEST'
--
-- USO:
-- - Admin emite saldo via POST /admin/test-currency/emit
-- - Usuários gastam TEST normalmente
-- - SplitEngine processa splits normalmente
-- - Ledger registra tudo normalmente
--
-- GATE DE VALIDAÇÃO:
-- - TestCurrencyService valida que apenas TEST seja emitida
-- - Rotas admin exigem role 'admin'
-- - Ambiente de produção pode bloquear emissão de TEST (futuro)
--
-- ===========================
-- COMENTÁRIOS
-- ===========================
COMMENT ON COLUMN accounts.currency IS 'Moeda da conta. Valores: BRL, USD, EUR (produção) ou TEST (desenvolvimento/teste)';
COMMENT ON COLUMN transactions.currency IS 'Moeda da transação. Valores: BRL, USD, EUR (produção) ou TEST (desenvolvimento/teste)';

-- ===========================
-- NOTA TÉCNICA
-- ===========================
-- Esta migration NÃO altera o schema físico.
-- Apenas documenta o uso da moeda TEST.
-- O schema já suporta qualquer VARCHAR(3) como currency.
--
-- Para usar TEST:
-- 1. Criar conta com currency='TEST'
-- 2. Emitir saldo via TestCurrencyService
-- 3. Usar normalmente em transações
-- 4. SplitEngine processa normalmente



