# RESTORE SCRIPT - reads from BACKUP_SRC_FULL.txt
# Place BACKUP_SRC_FULL.txt in C:/unificard/ and run this script
# from C:/unificard/ directory

$ErrorActionPreference = "Stop"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
$backupPath = "C:/unificard/BACKUP_SRC_FULL.txt"

if (-not (Test-Path $backupPath)) {
    Write-Error "BACKUP_SRC_FULL.txt not found at $backupPath"
    exit 1
}

Write-Output "Reading backup file..."
$lines = [System.IO.File]::ReadAllLines($backupPath)
Write-Output "Total lines: $($lines.Length)"

# Parse file boundaries
$headers = @()
for ($i = 0; $i -lt $lines.Length; $i++) {
    $line = $lines[$i].TrimStart([char]0xFEFF)
    if ($line -match '^=+\s+C:\\unificard\\backend\\src\\(.+?\.ts)\s+=+$') {
        $headers += [PSCustomObject]@{ Index = $i; RelPath = $Matches[1] }
    }
}
Write-Output "Found $($headers.Length) files in backup"

# Files that need restoration (missing from current src)
$toRestore = @(
    "adapters\pix\pix-adapter.ts",
    "commands\catalog.commands.ts",
    "commands\concept.commands.ts",
    "commands\financial.commands.ts",
    "commands\index.ts",
    "config\test-override-users.ts",
    "contracts\marketplace\B2BCommercialContract.v2.contract.ts",
    "contracts\marketplace\CheckoutIntent.v2.contract.ts",
    "contracts\marketplace\EconomicEvent.v2.contract.ts",
    "contracts\marketplace\RegionalActivationRule.v2.contract.ts",
    "contracts\marketplace\RegionalImpactMetrics.v2.contract.ts",
    "contracts\marketplace\SLAContract.v2.contract.ts",
    "contracts\marketplace\ServiceBooking.contract.ts",
    "contracts\marketplace\ServiceOffering.contract.ts",
    "contracts\marketplace\_canonical\money.types.ts",
    "contracts\marketplace\canonical.ts",
    "contracts\marketplace\mappers\b2b-commercial-contract.v1-to-v2.ts",
    "contracts\marketplace\mappers\regional-activation-rule.v1-to-v2.ts",
    "contracts\marketplace\mappers\regional-impact-metrics.v1-to-v2.ts",
    "core\actors\actor.helpers.ts",
    "core\alerts\alert-router.ts",
    "core\bank\assert-cents.ts",
    "core\bank\authorship\build-minimal-authorship.ts",
    "core\bank\ports\bank-authorship.types.ts",
    "core\catalog\canonical\canonical-concept-resolution-audit.ts",
    "core\catalog\canonical\canonical-concept-resolution-queue.service.ts",
    "core\catalog\canonical\canonical-concept.types.ts",
    "core\catalog\canonical\canonical-match-suggestion.service.ts",
    "core\catalog\canonical\canonical-product-commerce-guard.ts",
    "core\catalog\canonical\canonical-product-creation.pipeline.ts",
    "core\catalog\canonical\canonical-product-creation.service.ts",
    "core\catalog\canonical\canonical-product-db.types.ts",
    "core\catalog\canonical\canonical-product-events.repository.ts",
    "core\catalog\canonical\canonical-product-readiness.ts",
    "core\catalog\canonical\canonical-product.repository.ts",
    "core\checkout\event-organizer-resolver.ts",
    "core\compliance\authority-decision-audit.repository.ts",
    "core\compliance\authority-decision.service.ts",
    "core\compliance\authority-decision.types.ts",
    "core\db\table-classification.ts",
    "core\economy\accounts\account.service.ts",
    "core\events\b2b-payment-event-id.ts",
    "core\events\event-economy.service.ts",
    "core\events\event-economy.types.ts",
    "core\events\event-handler-failure.repository.ts",
    "core\events\event-outbox.processor.ts",
    "core\events\event-outbox.repository.ts",
    "core\events\event-payment-execution.service.ts",
    "core\events\event-payment.types.ts",
    "core\events\event-refund-chargeback.service.ts",
    "core\events\event-split-declarative.service.ts",
    "core\events\handler-failure.processor.ts",
    "core\events\outbox-metrics.routes.ts",
    "core\events\outbox-metrics.service.ts",
    "core\events\payment-events-queue.ts",
    "core\features\use-bank-regional-fund.ts",
    "core\financial\account-locks.ts",
    "core\financial\payout-safety.ts",
    "core\financial\transfer-limits.ts",
    "core\financial\withdrawal-velocity.ts",
    "core\http\canonical-http-error.ts",
    "core\intent\intent-draft.routes.ts",
    "core\intent\intent-execute-idempotency.ts",
    "core\intent\intent-execute.routes.ts",
    "core\navigation\n1-query.adapter.ts",
    "core\navigation\n2-governance.service.ts",
    "core\navigation\n2-query.adapter.ts",
    "core\navigation\navigation-offers.list.ts",
    "core\navigation\navigation.routes.ts",
    "core\observability\financial-anomaly-detector.ts",
    "core\observability\financial-audit.ts",
    "core\observability\financial-health.ts",
    "core\observability\financial-logger.ts",
    "core\observability\financial-metrics.ts",
    "core\observability\financial-operations-monitor.ts",
    "core\observability\handler-metrics.routes.ts",
    "core\observability\handler-metrics.service.ts",
    "core\observability\ledger-integrity-monitor.ts",
    "core\observability\marketplace-store-onboarding.observability.ts",
    "core\observability\ssot-observability.util.ts",
    "core\ontology\concept-governance.service.ts",
    "core\ontology\n0-domains.ts",
    "core\ontology\n1-governance.service.ts",
    "core\procurement-campaign\procurement-campaign.module.ts",
    "core\profile\__tests__\category-navigation-bridge.test.ts",
    "core\profile\category-navigation-bridge.ts",
    "core\reconciliation\financial-reconciliation.ts",
    "core\reconciliation\reconciliation-metrics.routes.ts",
    "core\reconciliation\reconciliation.service.ts",
    "core\reporting\ai\risk-scoring-engine.ts",
    "core\sagas\handlers\saga-compensation.handler.ts",
    "core\sagas\saga-metrics.routes.ts",
    "core\semantic\graph-governance.service.ts",
    "core\semantic\graph.adapter.ts",
    "core\semantic\semantic-http.ts",
    "core\semantic\semantic-metrics.repository.ts",
    "core\semantic\semantic-policy.repository.ts",
    "core\semantic\semantic.adapter.ts",
    "core\semantic\semantic.errors.ts",
    "core\semantic\semantic.policy.ts",
    "core\social\actor-type.ts",
    "core\tenants\tenant-context-bootstrap.service.ts",
    "core\unifybank\bank-http.routes.ts",
    "modules\alerts\financial-alert-repository.ts",
    "modules\audit\financial-audit-export.controller.ts",
    "modules\authority\authority.service.ts",
    "modules\bank-settlement\bank-settlement-repository.ts",
    "modules\bank\bank-http-money.ts",
    "modules\bank\bank-http.contracts.ts",
    "modules\bank\bank-ledger.service.ts",
    "modules\bank\bank-maintenance.service.ts",
    "modules\bank\bank-transaction-read.repository.ts",
    "modules\bank\integer-cents-from-db.ts",
    "modules\bank\ledger-compensation.service.ts",
    "modules\circuit-breaker\financial-circuit-breaker-guard.ts",
    "modules\circuit-breaker\financial-circuit-breaker-repository.ts",
    "modules\concept-resolution\concept-resolution-context.ts",
    "modules\concept-resolution\concept-resolution.service.ts",
    "modules\concept-resolution\concept-resolution.types.ts",
    "modules\concept-resolution\concept-slug-resolve.service.ts",
    "modules\concept-resolution\index.ts",
    "modules\disputes\financial-dispute-repository.ts",
    "modules\disputes\financial-dispute.controller.ts",
    "modules\escrow\escrow.service.ts",
    "modules\events\CheckoutConsumptionService.ts",
    "modules\events\CheckoutTicketService.ts",
    "modules\events\checkout-consumption.service.ts",
    "modules\events\checkout-ticket.service.ts",
    "modules\events\event-lifecycle.routes.ts",
    "modules\freezes\financial-freeze-repository.ts",
    "modules\freezes\financial-freeze.controller.ts",
    "modules\gateway\gateway-webhook-repository.ts",
    "modules\gateway\payment-event-processor.ts",
    "modules\gateway\payment-event-resolver.ts",
    "modules\gateway\pix-webhook.controller.ts",
    "modules\governance-funding-commitment\governance-funding-commitment.repository.ts",
    "modules\governance-funding\governance-funding.repository.ts",
    "modules\governance-funding\governance-funding.service.ts",
    "modules\governance\governance-financial-action-repository.ts",
    "modules\governance\governance-proposal-repository.ts",
    "modules\governance\governance-proposal.controller.ts",
    "modules\groups\groups-membership.helper.ts",
    "modules\groups\policies\group-creation-policy.ts",
    "modules\identity\actor-ssot.service.ts",
    "modules\identity\actor-writer.service.ts",
    "modules\identity\index.ts",
    "modules\ledger-snapshots\ledger-snapshot-repository.ts",
    "modules\ledger\ledger.repository.ts",
    "modules\logistics\index.ts",
    "modules\logistics\logistics.types.ts",
    "modules\logistics\multi-leg.service.ts",
    "modules\logistics\transport-demand.service.ts",
    "modules\logistics\transport-planner.service.ts",
    "modules\logistics\vehicle-matcher.service.ts",
    "modules\marketplace\adapters\concept-offer-refs.adapter.ts",
    "modules\marketplace\application\dispatch\commands\accept-dispatch.command.ts",
    "modules\marketplace\application\dispatch\commands\dispatch-service-request.command.ts",
    "modules\marketplace\application\dispatch\queries\get-request-status.query.ts",
    "modules\marketplace\application\dispatch\queries\get-request-timeline.query.ts",
    "modules\marketplace\application\dispatch\queries\list-eligible-providers.query.ts",
    "modules\marketplace\application\events\event-bus.ts",
    "modules\marketplace\application\events\index.ts",
    "modules\marketplace\application\events\marketplace-event-bus.ts",
    "modules\marketplace\application\handlers\capacity-dispatch-accepted.handler.ts",
    "modules\marketplace\application\handlers\economic-dispatch-accepted.handler.ts",
    "modules\marketplace\application\handlers\orders-dispatch-accepted.handler.ts",
    "modules\marketplace\application\handlers\register-marketplace-dispatch-accepted-handlers.ts",
    "modules\marketplace\application\services\capacity-application.service.ts",
    "modules\marketplace\application\services\catalog-application.service.ts",
    "modules\marketplace\application\services\commerce-operations-application.service.ts",
    "modules\marketplace\application\services\company-application.service.ts",
    "modules\marketplace\application\services\discovery-application.service.ts",
    "modules\marketplace\application\services\dispatch-application.service.ts",
    "modules\marketplace\application\services\marketplace-orchestration.service.ts",
    "modules\marketplace\application\services\offerings-application.service.ts",
    "modules\marketplace\application\services\orders-application.service.ts",
    "modules\marketplace\application\services\payments-application.service.ts",
    "modules\marketplace\application\services\regional-capacity-application.service.ts",
    "modules\marketplace\attribution.service.ts",
    "modules\marketplace\business-template-store-onboarding-plan.ts",
    "modules\marketplace\core\event-bus.ts",
    "modules\marketplace\core\event-metrics.ts",
    "modules\marketplace\core\event-registry.ts",
    "modules\marketplace\core\event-timeline.ts",
    "modules\marketplace\core\events.ts",
    "modules\marketplace\core\events\capacity-events.ts",
    "modules\marketplace\core\events\payment-events.ts",
    "modules\marketplace\core\events\service-events.ts",
    "modules\marketplace\core\events\trust-events.ts",
    "modules\marketplace\core\events\voucher-events.ts",
    "modules\marketplace\domain\b2b\marketplace-b2b.service.ts",
    "modules\marketplace\domain\capacity\marketplace-capacity.service.ts",
    "modules\marketplace\domain\capacity\marketplace-compensation.service.ts",
    "modules\marketplace\domain\capacity\marketplace-expansion.service.ts",
    "modules\marketplace\domain\company\marketplace-company.service.ts",
    "modules\marketplace\domain\dispatch\events\dispatch-accepted.event.ts",
    "modules\marketplace\domain\dispatch\marketplace-dispatch-presence.service.ts",
    "modules\marketplace\domain\dispatch\marketplace-dispatch.service.ts",
    "modules\marketplace\domain\economic\marketplace-economic.service.ts",
    "modules\marketplace\domain\industry\marketplace-industry.service.ts",
    "modules\marketplace\domain\offerings\marketplace-offerings.service.ts",
    "modules\marketplace\domain\orders\marketplace-orders.service.ts",
    "modules\marketplace\domain\payments\marketplace-payments.service.ts",
    "modules\marketplace\domain\pricing\marketplace-pricing.service.ts",
    "modules\marketplace\domain\production\marketplace-production.service.ts",
    "modules\marketplace\domain\services\marketplace-service-lifecycle.service.ts",
    "modules\marketplace\domain\sla\marketplace-sla.service.ts",
    "modules\marketplace\domain\subscriptions\marketplace-subscriptions.service.ts",
    "modules\marketplace\domain\types\domain-types.ts",
    "modules\marketplace\domain\types\index.ts",
    "modules\marketplace\domain\types\mappers.ts",
    "modules\marketplace\domain\vouchers\marketplace-vouchers.interfaces.ts",
    "modules\marketplace\domain\vouchers\marketplace-vouchers.service.ts",
    "modules\marketplace\economic-identity.repository.ts",
    "modules\marketplace\economic-identity.service.ts",
    "modules\marketplace\facades\marketplace-b2b.facade.ts",
    "modules\marketplace\facades\marketplace-catalog.facade.ts",
    "modules\marketplace\inventory-movement-http.schemas.ts",
    "modules\marketplace\marketplace-commercial.service.ts",
    "modules\marketplace\marketplace-compliance.service.ts",
    "modules\marketplace\marketplace-contextual.routes.ts",
    "modules\marketplace\marketplace-contextual.service.ts",
    "modules\marketplace\marketplace-fund.service.ts",
    "modules\marketplace\marketplace-legacy-memory-order-flag.ts",
    "modules\marketplace\marketplace-operations.service.ts",
    "modules\marketplace\marketplace-plugin.repository.ts",
    "modules\marketplace\marketplace-plugin.service.ts",
    "modules\marketplace\marketplace-regional-fund-bank.helpers.ts",
    "modules\marketplace\marketplace-revenue.service.ts",
    "modules\marketplace\marketplace-seed.ts",
    "modules\marketplace\marketplace-services.service.ts",
    "modules\marketplace\marketplace-templates.service.ts",
    "modules\marketplace\marketplace-terminal.service.ts",
    "modules\marketplace\marketplace.module.ts",
    "modules\marketplace\payment-transaction.repository.ts",
    "modules\marketplace\product-concept-guard.ts",
    "modules\marketplace\product-visibility.service.ts",
    "modules\marketplace\regional-activation-events.repository.ts",
    "modules\marketplace\regional-activation-events.service.ts",
    "modules\marketplace\regional-activation.repository.ts",
    "modules\marketplace\regional-activation.service.ts",
    "modules\marketplace\regional-fund.repository.ts",
    "modules\marketplace\regional-fund.service.ts",
    "modules\marketplace\regional-impact.repository.ts",
    "modules\marketplace\regional-impact.service.ts",
    "modules\marketplace\resource-compensation.service.ts",
    "modules\marketplace\routes\marketplace-b2b-contracts.routes.ts",
    "modules\marketplace\routes\marketplace-identity.routes.ts",
    "modules\marketplace\routes\marketplace-sla.routes.ts",
    "modules\marketplace\service-booking.service.ts",
    "modules\marketplace\services\marketplace-capacity.service.ts",
    "modules\marketplace\services\marketplace-catalog.service.ts",
    "modules\marketplace\services\marketplace-checkout.service.ts",
    "modules\marketplace\services\marketplace-company.service.ts",
    "modules\marketplace\services\marketplace-discovery.service.ts",
    "modules\marketplace\services\marketplace-dispatch.service.ts",
    "modules\marketplace\services\marketplace-governance.service.ts",
    "modules\marketplace\services\marketplace-orders.service.ts",
    "modules\marketplace\services\marketplace-payments.service.ts",
    "modules\marketplace\services\marketplace-pricing.service.ts",
    "modules\marketplace\services\marketplace-services.service.ts",
    "modules\marketplace\services\marketplace-vouchers.service.ts",
    "modules\marketplace\state\marketplace-state.adapter.ts",
    "modules\marketplace\store-product.repository.ts",
    "modules\marketplace\store-product.service.ts",
    "modules\marketplace\tenant-concept-offerings.repository.ts",
    "modules\marketplace\voucher.service.ts",
    "modules\metrics\financial-metrics-repository.ts",
    "modules\observability\financial-dashboard.controller.ts",
    "modules\observability\financial-health.controller.ts",
    "modules\observability\financial-observability.controller.ts",
    "modules\observability\financial-operations-panel.controller.ts",
    "modules\observability\financial-simulator.controller.ts",
    "modules\orders\order-saga.service.ts",
    "modules\payments\payment-intent-repository.ts",
    "modules\payouts\payout-repository.ts",
    "modules\rate-limit\financial-rate-limit-guard.ts",
    "modules\rate-limit\financial-rate-limit-repository.ts",
    "modules\reconciliation\bank-reconciliation.service.ts",
    "modules\reconciliation\gateway-reconciliation.service.ts",
    "modules\reconciliation\reconciliation-discrepancy.repository.ts",
    "modules\reconciliation\reconciliation-dispute-audit.util.ts",
    "modules\reconciliation\reconciliation-dispute-event.repository.ts",
    "modules\reconciliation\reconciliation-dispute.repository.ts",
    "modules\reconciliation\reconciliation-dispute.routes.ts",
    "modules\reconciliation\reconciliation-dispute.service.ts",
    "modules\reconciliation\reconciliation-dispute.types.ts",
    "modules\reconciliation\reconciliation-engine.service.ts",
    "modules\reconciliation\reconciliation-trigger.processor.ts",
    "modules\reconciliation\reconciliation.repository.ts",
    "modules\reconciliation\reconciliation.service.ts",
    "modules\reconciliation\reconciliation.types.ts",
    "modules\reporting\reporting-bank-aggregates.ts",
    "modules\reversal\reversal.repository.ts",
    "modules\reversal\reversal.service.ts",
    "modules\rides\shared\publish-ride-event.ts",
    "modules\rides\shared\ride-authority.ts",
    "modules\risk-identity\actor-effective-block.ts",
    "modules\risk-identity\actor-events.repository.ts",
    "modules\risk-identity\actor-risk.repository.ts",
    "modules\risk-identity\risk-engine.service.ts",
    "modules\risk-identity\risk-financial-gate.ts",
    "modules\risk-identity\risk-hooks.ts",
    "modules\risk-identity\risk-limits.repository.ts",
    "modules\risk-identity\risk-permissions.ts",
    "modules\risk\financial-risk-repository.ts",
    "modules\schedule\schedule.types.ts",
    "modules\services\services-discovery-metrics.service.ts",
    "modules\services\services-discovery.routes.ts",
    "modules\services\services-discovery.service.ts",
    "modules\services\services-discovery.types.ts",
    "modules\sla\financial-sla-repository.ts",
    "modules\treasury-split\treasury-split-config.repository.ts",
    "modules\treasury-split\treasury-split.service.ts",
    "modules\treasury\treasury-account-repository.ts",
    "modules\treasury\treasury-account.controller.ts",
    "modules\treasury\treasury-distribution-repository.ts",
    "modules\votes\votes.types.ts",
    "modules\work\work-event-outbox.helper.ts",
    "scripts\actor-responsibility-phase3.ts",
    "scripts\backfill-category-n1-mapping.ts",
    "scripts\backfill-concepts-bootstrap.ts",
    "scripts\backfill-concepts-n0-domain.ts",
    "scripts\backfill-e2e-mint-ledger-debits.ts",
    "scripts\backfill-global-user-links.ts",
    "scripts\backfill-n0-from-legacy.ts",
    "scripts\backfill-payment-splits-to-bank.ts",
    "scripts\category-n1-explicit-registry.ts",
    "scripts\e2e-incentive-bank-checklist.ts",
    "scripts\fund-regional-fund-bank-from-reserve.ts",
    "scripts\n2-expansion-plan21.data.ts",
    "scripts\normalize-category-concepts.ts",
    "scripts\rebuild-inventory-balances.ts",
    "scripts\remove-deprecated-context-nutricao.ts",
    "scripts\report-rides-vehicles-concept-mapping.ts",
    "scripts\run-category-integrity-checks.ts",
    "scripts\seed-category-relations.ts",
    "scripts\seed-minimal-social.ts",
    "scripts\seed-n2-governed.ts",
    "scripts\validate-financial-flow-real.ts",
    "scripts\validate-profile-n1.ts",
    "scripts\verify-simple-tx-double-entry.ts",
    "services\events\tests\event-checkout-hardening.test.ts",
    "workers\bank-settlement-worker.ts",
    "workers\event-outbox-worker.ts",
    "workers\financial-alert-worker.ts",
    "workers\financial-metrics-worker.ts",
    "workers\governance-execution-worker.ts",
    "workers\governance-financial-action-worker.ts",
    "workers\governance-funding-commitment-worker.ts",
    "workers\governance-funding-worker.ts",
    "workers\handler-failure-worker.ts",
    "workers\idempotency-cleanup-worker.ts",
    "workers\ledger-snapshot-worker.ts",
    "workers\payment-worker.ts",
    "workers\payout-worker.ts",
    "workers\reconciliation-engine-worker.ts",
    "workers\reconciliation-scheduled.worker.ts",
    "workers\reconciliation-worker.ts",
    "workers\release-worker.ts",
    "workers\reversal-worker.ts",
    "workers\risk-analysis-worker.ts",
    "workers\risk-identity-reconcile.worker.ts",
    "workers\saga-timeout.worker.ts",
    "workers\settlement-worker.ts",
    "workers\sla-monitor-worker.ts",
    "workers\treasury-distribution-worker.ts",
    "workers\treasury-split-worker.ts",
)

$created = 0; $skipped = 0; $errors = 0

foreach ($rel in $toRestore) {
    # Find header for this file
    $header = $headers | Where-Object { $_.RelPath -eq $rel } | Select-Object -First 1
    if (-not $header) {
        Write-Warning "NOT FOUND in backup: $rel"
        $errors++
        continue
    }
    
    # Find content boundaries
    $nextHeader = $headers | Where-Object { $_.Index -gt $header.Index } | Sort-Object Index | Select-Object -First 1
    $endIdx = if ($nextHeader) { $nextHeader.Index - 1 } else { $lines.Length - 1 }
    
    # Extract content
    $content = if ($endIdx -gt $header.Index) {
        [string]::Join("`n", $lines[($header.Index + 1)..$endIdx]).TrimEnd()
    } else { "" }
    
    # Write file
    $destPath = "C:\unificard\backend\src\" + $rel
    $destDir = [System.IO.Path]::GetDirectoryName($destPath)
    
    if (-not [System.IO.Directory]::Exists($destDir)) {
        [System.IO.Directory]::CreateDirectory($destDir) | Out-Null
    }
    
    [System.IO.File]::WriteAllText($destPath, $content, $utf8NoBom)
    Write-Output "CREATED: $rel"
    $created++
}

Write-Output ""
Write-Output "=== SUMMARY ==="
Write-Output "Created: $created"
Write-Output "Not found in backup: $errors"  
Write-Output "Done."
