// src/core/social/ports/actor-effect.port.ts
/**
 * Port: Actor Effect
 * 
 * Re-exporta tipos de effects de actor.
 * Implementação real está em @modules/social
 */

export enum ActorEffect {
  FEED_ITEM_CREATED = 'FEED_ITEM_CREATED',
  FEED_ITEM_UPDATED = 'FEED_ITEM_UPDATED',
  PROJECT_CREATED = 'PROJECT_CREATED',
  PROJECT_UPDATED = 'PROJECT_UPDATED',
  JOB_POSTED = 'JOB_POSTED',
  CTA_PUBLISHED = 'CTA_PUBLISHED',
  VOTE_REGISTERED = 'VOTE_REGISTERED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  GROUP_FUNDS_UPDATED = 'GROUP_FUNDS_UPDATED',
  EVENT_ANNOUNCED = 'EVENT_ANNOUNCED',
  SERVICE_CREATED = 'SERVICE_CREATED',
  SERVICE_ACTIVATED = 'SERVICE_ACTIVATED',
  SERVICE_UPDATED = 'SERVICE_UPDATED',
  SERVICE_AVAILABILITY_CREATED = 'SERVICE_AVAILABILITY_CREATED',
  SERVICE_AVAILABILITY_UPDATED = 'SERVICE_AVAILABILITY_UPDATED',
  SERVICE_BOOKING_REQUESTED = 'SERVICE_BOOKING_REQUESTED',
  SERVICE_BOOKING_CANCELLED = 'SERVICE_BOOKING_CANCELLED',
  SERVICE_BOOKING_ACCEPTED = 'SERVICE_BOOKING_ACCEPTED',
  SERVICE_BOOKING_REJECTED = 'SERVICE_BOOKING_REJECTED',
  SERVICE_PAYMENT_REQUESTED = 'SERVICE_PAYMENT_REQUESTED',
  SERVICE_PAYMENT_CANCELLED = 'SERVICE_PAYMENT_CANCELLED',
  SERVICE_PAYMENT_EXECUTED = 'SERVICE_PAYMENT_EXECUTED',
  SERVICE_PAYMENT_SPLIT_APPLIED = 'SERVICE_PAYMENT_SPLIT_APPLIED',
  OPPORTUNITY_DISPATCHED = 'OPPORTUNITY_DISPATCHED',
  OPPORTUNITY_DISPATCH_RESPONDED = 'OPPORTUNITY_DISPATCH_RESPONDED',
  IMPACT_RECORDED = 'IMPACT_RECORDED',
  NOTIFICATION_SENT = 'NOTIFICATION_SENT',
  AVAILABILITY_CONFLICT_DETECTED = 'AVAILABILITY_CONFLICT_DETECTED',
  REPUTATION_UPDATED = 'REPUTATION_UPDATED',
}





